services:
  postgres:
    image: postgres:17-bookworm
    restart: always
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5434:5432"
    volumes:
      - ./apps/api/src/adapters/database/SQL/01_criar_tbl_permissao.sql:/docker-entrypoint-initdb.d/01_criar_tbl_permissao.sql
      - ./apps/api/src/adapters/database/SQL/02_criar_tbl_perfil.sql:/docker-entrypoint-initdb.d/02_criar_tbl_perfil.sql
      - ./apps/api/src/adapters/database/SQL/03_criar_tbl_usuario.sql:/docker-entrypoint-initdb.d/03_criar_tbl_usuario.sql

  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    hostname: codefire-DEV
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - 5672:5672
      - 15672:15672

  mongo:
    image: mongo:8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - 27017:27017
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8087:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:123456@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
