services:
  postgres:
    image: postgres:17-bookworm
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5434:5432"
    volumes:
      - ./apps/api/src/adapters/database/SQL/01_criar_tbl_permissao.sql:/docker-entrypoint-initdb.d/01_criar_tbl_permissao.sql
      - ./apps/api/src/adapters/database/SQL/02_criar_tbl_perfil.sql:/docker-entrypoint-initdb.d/02_criar_tbl_perfil.sql
      - ./apps/api/src/adapters/database/SQL/03_criar_tbl_usuario.sql:/docker-entrypoint-initdb.d/03_criar_tbl_usuario.sql

  rabbitmq:
    image: rabbitmq:4-management
    hostname: codefire-DEV
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    ports:
      - 5673:5672
      - 15672:15672
